# 数据操作和预处理

## 数据操作
深度学习存储和操作数据的主要接⼝是张量（n维数组）。它提供了各种功能，包括基本数学运算、⼴播、索引、切⽚、内存节省和转换其他Python对象。

### 索引和切片
第一个元素的索引是0，最后一个元素索引是-1。
可以用[-1]选择最后一个元素，可以用[1:3]选择第二个和第三个元素
eg.
    访问一个具体元素  [1,2]
    访问一行元素  [1,:]
    访问一列元素  [:,1]
    访问连续子区域   [1:3,1:]
    访问间隔区域：如每隔3行2列访问元素  [::3,::2]

张量表示由⼀个数值组成的数组，这个数组可能有多个维度。具有一个轴的张量对应数学上的向量（vector）； 具有两个轴的张量对应数学上的矩阵（matrix）；具有两个轴以上的张量没有特殊的数学名称。

### 数据创建

In [43]:
import torch

arange 创建指定维度向量

In [44]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

shape 访问张量（沿每个轴的长度）的形状

In [45]:
x.shape

torch.Size([12])

number of element，计算总数

In [46]:
x.numel()

12

numpy中可以用 size 可以计算张量元素总数

In [47]:
import numpy as np
x = np.array([8,7,6,5])
x.size

4

reshape 可以改变张量形状且不改变元素值

In [48]:
x = torch.arange(12)
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

全0/1元素

In [49]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [50]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

随机创建指定形状张量

In [51]:
torch.randn(3,4)

tensor([[ 0.9513,  0.6109, -1.3531,  1.1344],
        [-0.3208,  0.6436,  0.1814,  1.3660],
        [ 0.0834,  1.3743,  0.6126, -0.5463]])

torch.tensor([]) 创建具体张量，嵌套链表形式

In [52]:
torch.tensor([[1,2,3,4],[2,3,4,5],[9,8,7,6]])

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [9, 8, 7, 6]])

### 数据运算

+、-、*、/、**都是按照元素运算

这里的*是对应元素相乘，和数学上的矩阵乘法不同

In [53]:
x = torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x*y,x-y,x+y,x/y,x**y

(tensor([ 2.,  4.,  8., 16.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 3.,  4.,  6., 10.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [ ]:
x1 = torch.tensor([[1,2],[4,8]])
y1 =torch.tensor([[2,2],[2,2]])
x1@y1   #矩阵乘法（行*列）
x1*y1   #哈达玛积 （逐元素相乘）

(tensor([[ 6,  6],
         [24, 24]]),
 tensor([[ 2,  4],
         [ 8, 16]]))

In [ ]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

把多个张量连接在一起，用torch.cat()，dim指定维度（dim=0是按行连接，dim=1是按列连接）

In [ ]:
x= torch.arange(12, dtype=torch.float32).reshape((3,4))
y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

逻辑运算符可构建二元张量

In [ ]:
x==y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量的所有元素求和会产生一个只有一个元素的张量

In [ ]:
x.sum()

tensor(66.)

### 广播机制
对于形状不同的张量，广播机制会让不同形状张量转换成相同形状计算

reshape(shape)，一般shape1会以一个元组，如（3，1）传入
也可以直接reshape(3，1)

In [ ]:
a =torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

计算时会将a和b广播为一个3*2的矩阵再计算

In [ ]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 数据读取和写入
第一个元素的索引是0，最后一个元素索引是-1。

In [ ]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
x[-1],x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [ ]:
x[1,2]=9  #按索修改元素
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
x[0:2,:]=12    #按切片修改元素
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 节省内存
运行一些操作可能导致为新结果分配内存
如果Y=Y+X，将取消引用Y指向的张量，指向新分配的内存处张量

In [ ]:
before = id(y)
y=y+x
id(y)==before

False

原地操作：可使用切片表示法将操作的结果分配给先前分配的数组
Y[:]=<expression>

In [ ]:
z=torch.zeros_like(y)
print('id(z):',id(z))
z[:]=x+y
print('id(z):',id(z))

id(z): 2366975131184
id(z): 2366975131184


也可以使用 y+=x 来减少内存开销

In [ ]:
before = id(y)
y+=x
id(y)==before

True

### 类型转换
可以将深度学习框架下张量转换成numpy张量(ndarray)

In [ ]:
A=x.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

大小为1的张量转换成python标量可使用item1函数或python1内置函数

In [ ]:
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 数据预处理

### 创建.csv文件（逗号分隔符）

In [ ]:
import os
os.makedirs(os.path.join('..','data'),exist_ok=True)   
#创建文件夹在父文件夹下，文件存在也不报错
data_file= os.path.join('..','data','house_tiny.csv')
#文件路径
with open(data_file,'w')as f:    
#写入文件，若文件不存在则创建，若存在则覆盖
    f.write('NumRooms,Alley,Price\n')  #写入表头
    f.write('NA,Pave,127500\n')         #写入数据
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

### 从创建的文件中读取数据

In [ ]:
import pandas as pd
data=pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


### 处理缺失值

“NaN”
1. 插值法：用替代值弥补缺失值
2. 删除法：忽略缺失值

In [ ]:
inputs,outputs= data.iloc[:,0:2],data.iloc[:,2]
#iloc选取值，fillna()填充缺失值
inputs = inputs.fillna(inputs.mean(numeric_only=True))  #用均值填充缺失值
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


对于类别值或离散值，可以将‘NaN’看作一个类别

In [ ]:
inputs= pd.get_dummies(inputs,dummy_na=True)  
# 将分类变量转化为one-hot编码(仅0/1)
# dummy_na=True表示将缺失值单独编码，即保留缺失值信息
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


### 转换成张量格式

In [ ]:
import torch
inputs=inputs.astype(int)
x,y=torch.tensor(inputs.values),torch.tensor(outputs.values)
x,y

(tensor([[3, 1, 0],
         [2, 0, 1],
         [4, 0, 1],
         [3, 0, 1]]),
 tensor([127500, 106000, 178100, 140000]))