# 数据处理和操作

访问一个元素  [1,2]
访问一行元素  [1,:]
访问一列元素  [:,1]
访问连续子区域   [1:3,1:]
访问间隔区域：如每隔3行2列访问元素  [::3,::2]

张量表示由⼀个数值组成的数组，这个数组可能有多个维度。具有一个轴的张量对应数学上的向量（vector）； 具有两个轴的张量对应数学上的矩阵（matrix）；具有两个轴以上的张量没有特殊的数学名称。

In [19]:
import torch

## 数据创建

In [20]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
x.shape

torch.Size([12])

In [22]:
x.numel()

12

In [23]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [24]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [25]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [26]:
torch.randn(3,4)

tensor([[-0.6188,  0.5161,  1.3446, -0.6485],
        [ 0.9563,  0.1695,  0.7093, -0.9072],
        [-1.0988,  1.7596,  0.1599,  1.3171]])

In [27]:
torch.tensor([[1,2,3,4],[2,3,4,5],[9,8,7,6]])

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [9, 8, 7, 6]])

## 数据运算