数据处理和操作

访问一个元素  [1,2]
访问一行元素  [1,:]
访问一列元素  [:,1]
访问连续子区域   [1:3,1:]
访问间隔区域：如每隔3行2列访问元素  [::3,::2]

张量表示由⼀个数值组成的数组，这个数组可能有多个维度。具有一个轴的张量对应数学上的向量（vector）； 具有两个轴的张量对应数学上的矩阵（matrix）；具有两个轴以上的张量没有特殊的数学名称。

In [ ]:
import torch

In [ ]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x.shape

torch.Size([12])

In [ ]:
x.numel()

12

In [ ]:
x = x.reshape(3,4)
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
torch.randn(3,4)

tensor([[-1.0436e+00, -5.5056e-01,  1.6383e+00, -1.7740e-03],
        [ 4.3182e-01, -8.6325e-01, -4.0605e-01, -1.0636e+00],
        [ 4.8440e-01,  2.7173e+00,  1.3761e-01,  1.5222e+00]])

In [ ]:
torch.tensor([[1,2,3,4],[2,3,4,5],[9,8,7,6]])

tensor([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [9, 8, 7, 6]])